### ISSUE TITLE
Exporting PDF's into their own folders

### ISSUE THREAD

**Issue by KieranBond** [KieranBond/PReticulated#5]
Add the ability to export all pages/pngs of a PDF into a folder for each individual PDF.

E.g,

If you export two PDF's called `testPDF` and `adifferenttestPDF`, a folder would be created in the destination with these names and the appropriate png's from each PDF would go into the correct folders

**Comment by mahditakrim** [comment]
Hi @KieranBond ,
May I take a look ?

**Comment by KieranBond** [comment]
@mahditakrim of course. Have a look at the Contributing document before you do, and then fork and create a merge request when you've had a go at it, tag me and reference the issue and I'll have a look :)

**Comment by mahditakrim** [comment]
What I figured out, you want each PDF page to be a png ?

**Comment by KieranBond** [comment]
@mahditakrim that is currently what it already does. What I want is the PNG's for each PDF to be in a folder with the name of the PDF

**Comment by mahditakrim** [comment]
@KieranBond , PNGs for each PDF to be in separate folder naming by PDF name, got it and I will try.

**Comment by KieranBond** [comment]
@mahditakrim sounds about right! Make sure you pull the latest changes before you start working on it!

**Comment by mahditakrim** [comment]
Dear @KieranBond ,
I just tried to build the project but got these errors and warnings:
![e1](https://user-images.githubusercontent.com/47906168/67780384-478f3600-fa7b-11e9-94be-335cc39791ce.png)
![e2](https://user-images.githubusercontent.com/47906168/67780385-478f3600-fa7b-11e9-86fd-e9df7f624ede.png)

**Comment by KieranBond** [comment]
Hi @mahditakrim 

I'm not quite sure what's happened there! It looks like your package manager has failed to install the libraries correctly. 

If I were you, I would have a look at the last error you've got (about using Package Restore). I wasn't able to get others to replicate this issue, so I believe it's something that's happened on your end.

What version of Visual Studio are you using?

**Comment by mahditakrim** [comment]
VS 2017-15.9.17

**Comment by KieranBond** [comment]
@mahditakrim 
> VS 2017-15.9.17

Have you attempted the Package Restore?

**Comment by KieranBond** [comment]
@mahditakrim so that is because you're using VS 2017, and the project is using C# 8.

Have a look [here](https://stackoverflow.com/questions/54701377/how-can-i-use-c-sharp-8-with-visual-studio-2017) for a solution - In short, you'll either have to update some NuGet packages or upgrade which version of Visual Studio you're using.

**Comment by mahditakrim** [comment]
So if I install the latest version of VS, it's done ?

**Comment by KieranBond** [comment]
@mahditakrim yes that hopefully should.

**Comment by KieranBond** [comment]
@mahditakrim I'm going to delete the above comments to help keep this issue clean - is that ok?

**Comment by mahditakrim** [comment]
Dear @KieranBond ,
 I tried to build and run the project and it worked but there is a bug (I think) in it.
When you want to convert another PDF in second time (or sometimes third time) it crashes with or without converting, I mean it's hard to tell what exactly this bug is but what I figured out so far is that it sometimes crashes after converting.

**Comment by KieranBond** [comment]
@mahditakrim if you could raise this as a separate issue with some details on how to re-produce it that would be great.

**Comment by mahditakrim** [comment]
> @mahditakrim if you could raise this as a separate issue with some details on how to re-produce it that would be great.

Ok , I think if you use a standard foreach loop instead of parallel and have a progress bar connected with it, it will prevent a lot of bugs and runtime misbehavior.

So if you are agree, I will make an issue pointing to loop change and setting a progress bar in the UI ?

**Comment by KieranBond** [comment]
@mahditakrim please refer to #6. The changes you're proposing are a different change to this issue.

**Comment by KieranBond** [comment]
Resolved by @mahditakrim  in #7
