### ISSUE TITLE
[BUG] Converting the same PDF multiple times crashes the app

### ISSUE THREAD

**Issue by KieranBond** [KieranBond/PReticulated#6]
From #5 's comments. 
>>@mahditakrim if you could raise this as a separate issue with some details on how to re-produce it >>that would be great.
>
>Ok , I think if you use a standard foreach loop instead of parallel and have a progress bar connected >with it, it will prevent a lot of bugs and runtime misbehavior.
>
>So if you are agree, I will make an issue pointing to loop change and setting a progress bar in the UI >

**Comment by KieranBond** [comment]
@mahditakrim, 

Removing the Parallel for loop will vastly reduce the speed of the app. 

My suggestion is to keep that there for speed.

Instead I think there's three solutions;

* Don't allow more than one instance of a file to be converted per run.
* Lock the file. 
* Duplicate the file's converted PNG's instead of reprocessing the file.

Preferably, I'd like to not take away capability and would rather the 3rd option as it won't slow down the app considerably (if at all) and isn't complicated to do. 

---

>setting a progress bar in the UI

If you wish to create a progress bar, feel free - but please create an issue for this and do a seperate pull request for this.

**Comment by mahditakrim** [comment]
So we don't agree.

**Comment by KieranBond** [comment]
> So we don't agree.

I'm not sure what exactly you're on about here?

Yes, the issue is there because we're using a parallel for loop - but the solution by removing it is not ideal, and instead we should use a different solution as otherwise the app will lose a lot of it's speed in processing more than one PDF.

**Comment by KieranBond** [comment]
@mahditakrim are you able to provide some steps to reproduce this please, as I've been unable to so far.

**Comment by mahditakrim** [comment]
@KieranBond ,
I literally can't remember the exact steps, I was testing the app in different modes and got some crashes at some point.
Just try to test the app in different scenarios,  probably you can get it.

**Comment by KieranBond** [comment]
Thanks @mahditakrim, 

I'm unable to replicate the issue I'm afraid so for now I will close it.

Feel free to re-open / create a new one if you do encounter it and can reproduce!
